### ISSUE TITLE
help it does not work

### ISSUE THREAD

**Issue by appledeej** [Bentechy66/midi-to-virtualpiano#1] opened 2019-03-14 11:10 UTC
This script is so bad and un-optimized, it takes 2 hours to parse a midi...

**Comment by Bentechy66** [comment] 2019-03-14 11:11
Hello! Thanks for your bug report. Please include a description of what you were doing at the time of parsing - it takes only a few seconds for a 15 minute long MIDI file for me. If you could include both the midi and the log file from the run that would be helpful.

Also, be sure to follow the guidelines for creating an issue:
## Bug reports

A bug is a _demonstrable problem_ that is caused by the code in the repository.
Good bug reports are extremely helpful - thank you!

Guidelines for bug reports:

1. **Use the GitHub issue search** &mdash; check if the issue has already been
   reported.

2. **Check if the issue has been fixed** &mdash; try to reproduce it using the
   latest `master` or development branch in the repository.

3. **Isolate the problem** &mdash; create a [reduced test
   case](http://css-tricks.com/reduced-test-cases/) and a live example.

A good bug report shouldn't leave others needing to chase you up for more
information. Please try to be as detailed as possible in your report. What is
your environment? What steps will reproduce the issue? What browser(s) and OS
experience the problem? What would you expect to be the outcome? All these
details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
>
> A summary of the issue and the browser/OS environment in which it occurs. If
> suitable, include the steps required to reproduce the bug.
>
> 1. This is the first step
> 2. This is the second step
> 3. Further steps, etc.
>
> `<url>` - a link to the reduced test case
>
> Any other information you want to share that is relevant to the issue being
> reported. This might include the lines of code that you have identified as
> causing the bug, and potential solutions (and your opinions on their
> merits).

Closing issue until further information recieved.

**Comment by appledeej** [comment] 2019-03-14 11:11
wait there is a bug in my computer?

**Closed by Bentechy66** 2019-03-14 11:11 UTC

**Comment by Bentechy66** [comment] 2019-03-14 11:12
Hi! Unfortunately it's hard to know whether your computer has a bug, however - if you're reporting a bug in the code, please include logs and the MIDI file you're parsing. Thanks!

**Comment by appledeej** [comment] 2019-03-14 11:13
go away mr meanie you put a bug in my computer

**Comment by Bentechy66** [comment] 2019-03-14 11:13
> go away mr meanie you put a bug in my computer

Deleting as off-topic
